const WORK_PROVIDER = 2
const FREELANCER = 1

const DRAFT_PROJECT_STATUS = 1
const ACTIVE_PROJECT_STATUS = 2
const DELETE_PROJECT_STATUS = 4
const PAUSE_PROJECT_STATUS = 5

export {
  WORK_PROVIDER,
  FREELANCER,
  DRAFT_PROJECT_STATUS,
  ACTIVE_PROJECT_STATUS,
  DELETE_PROJECT_STATUS,
  PAUSE_PROJECT_STATUS,
}
