// ONLY FOR DEVELOPMENT
export const IS_DEBUGGER_MODE = 'IS_DEBUGGER_MODE'
export const CHANGE_USER_ROLE = 'CHANGE_USER_ROLE'
export const OPEN_MOBILE_MENU = 'OPEN_MOBILE_MENU'
export const LOGOUT = 'LOGOUT'

export const IDLE_STATUS = 'idle'
export const LOADING_STATUS = 'loading'
export const SUCCESS_STATUS = 'success'
export const FAILURE_STATUS = 'failure'

export const FETCH_USER = 'FETCH_USER'
export const CREATE_USER_PROFILE = 'CREATE_USER_PROFILE'
export const CREATE_USER_PROFILE_SUCCESS = 'CREATE_USER_PROFILE_SUCCESS'
export const CREATE_USER_PROFILE_FAILURE = 'CREATE_USER_PROFILE_FAILURE'
export const _SUCCESS = '_SUCCESS'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const START_ASYNC_CALL = 'START_ASYNC_CALL'
export const STOP_ASYNC_CALL = 'STOP_ASYNC_CALL'
export const SIGN_UP = 'SIGN_UP'
export const UNSAVED_PROJECT = 'UNSAVED_PROJECT'
export const DRAFT_PROJECT = 'DRAFT_PROJECT'
export const REMOVE_DRAFT_PROJECT = 'REMOVE_DRAFT_PROJECT'
export const UPDATE_EMAILS = 'UPDATE_EMAILS'
export const UPDATE_EMAILS_SUCCESS = 'UPDATE_EMAILS_SUCCESS'
export const UPDATE_EMAILS_FAILURE = 'UPDATE_EMAILS_FAILURE'

export const UPDATE_WORK_INFORMATION = 'UPDATE_WORK_INFORMATION'

export const FETCH_FREELANCERS = 'FETCH_FREELANCERS'
export const FETCH_FREELANCERS_SUCCESS = 'FETCH_FREELANCERS_SUCCESS'
export const FETCH_FREELANCERS_FAILURE = 'FETCH_FREELANCERS_FAILURE'

export const MAKE_FREELANCER_FAVORITE = 'MAKE_FREELANCER_FAVORITE'

export const UPDATE_IMAGE = 'UPDATE_IMAGE'

export const CREATE_PROJECT = 'CREATE_PROJECT'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE'
export const RESET_PROJECT = 'RESET_PROJECT'

export const FETCH_PROJECTS_BY_STATUS = 'FETCH_PROJECTS_BY_STATUS'
export const FETCH_PROJECTS_BY_STATUS_SUCCESS =
  'FETCH_PROJECTS_BY_STATUS_SUCCESS'
export const FETCH_PROJECTS_BY_STATUS_FAILURE =
  'FETCH_PROJECTS_BY_STATUS_FAILURE'
export const UPDATE_PROJECT_STATUS = 'UPDATE_PROJECT_STATUS'
export const UPDATE_PROJECT_STATUS_SUCCESS = 'UPDATE_PROJECT_STATUS_SUCCESS'
export const UPDATE_PROJECT_STATUS_FAILURE = 'UPDATE_PROJECT_STATUS_FAILURE'

export const FETCH_PUBLIC_PROJECTS = 'FETCH_PUBLIC_PROJECTS'
export const FETCH_PUBLIC_PROJECTS_SUCCESS = 'FETCH_PUBLIC_PROJECTS_SUCCESS'
export const FETCH_PUBLIC_PROJECTS_FAILURE = 'FETCH_PUBLIC_PROJECTS_FAILURE'
export const SET_FILTERS = 'SET_FILTERS'
export const SELECT_PROJECT_TO_INVITE = 'SELECT_PROJECT_TO_INVITE'
export const RESET_PRE_SELECTED_PROJECT = 'RESET_PRE_SELECTED_PROJECT'
export const RESET_APPLIED = 'RESET_APPLIED'

export const APPLY_PROJECT = 'APPLY_PROJECT'
export const APPLY_PROJECT_SUCCESS = 'APPLY_PROJECT_SUCCESS'
export const APPLY_PROJECT_FAILURE = 'APPLY_PROJECT_FAILURE'

export const FETCH_APPLICATIONS = 'FETCH_APPLICATIONS'
export const FETCH_APPLICATIONS_SUCCESS = 'FETCH_APPLICATIONS_SUCCESS'
export const FETCH_APPLICATIONS_FAILURE = 'FETCH_APPLICATIONS_FAILURE'
